# Generated by Django 2.1.3 on 2018-12-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_auto_20181206_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart_item_model',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='shopping_cart_model',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='shopping_cart_model',
            name='ref_code',
        ),
    ]
