# Generated by Django 2.1.3 on 2018-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20181209_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart_item_model',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopping_cart_model',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopping_cart_model',
            name='ref_code',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
