# Generated by Django 2.1.3 on 2018-11-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='home_page/static/media/products_images'),
        ),
    ]
