# Generated by Django 2.1.3 on 2018-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181129_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
    ]
