# Generated by Django 2.1.3 on 2018-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField(default=True)),
                ('shipping_method', models.BooleanField(default=True)),
            ],
        ),
    ]
